sudo: false
# Set Ruby as the language so it doesn't download the pip things. Instead, let docker do that.
language: ruby

matrix:
  include:
    - install:
      - env | grep TRAVIS > .env
      - env | grep CI >> .env
      - docker-compose -f docker-compose.yml -f docker-compose.travis.yml run celery echo
      script: (docker-compose -f docker-compose.yml -f docker-compose.travis.yml up celery &); sleep 5; docker-compose -f docker-compose.yml -f docker-compose.travis.yml run web tox
      cache: pip
      services:
        - docker
      env:
        name: Python
    - install:
      - env | grep TRAVIS > .env
      - env | grep CI >> .env
      - docker build -t travis-watch -f ./travis/Dockerfile-travis-watch .
      - docker run --name travis-watch-container --env-file .env -e NODE_ENV=production -t travis-watch ./webpack_if_prod.sh
      - docker cp travis-watch-container:/src/webpack-stats.json .
      - docker cp travis-watch-container:/src/static/bundles ./static/bundles
      script: ./scripts/test/run_selenium_tests_travis.sh
      services:
        - docker
      env:
        name: Python-Selenium
    - install:
      - env | grep TRAVIS > .env
      - env | grep CI >> .env
      - docker build -t travis-watch -f ./travis/Dockerfile-travis-watch .
      script: bash ./travis/js_tests.sh
      services:
        - docker
      env:
        name: JavaScript
