sudo: false

# xenial for newer docker-compose https://blog.travis-ci.com/2018-11-08-xenial-release
dist: xenial

matrix:
  include:
    - language: ruby
      install:
      - env | grep TRAVIS > .env
      - env | grep CI >> .env
      script: docker-compose -f docker-compose.yml -f docker-compose.travis.yml run web tox
      services:
        - docker
      env:
        name: Python
    - install:
      - env | grep TRAVIS > .env
      - env | grep CI >> .env
      - docker build -t micromasters_watch -f ./Dockerfile-node .
      - docker build -t travis-watch -f ./travis/Dockerfile-travis-watch .
      - docker run --name travis-watch-container --env-file .env -e NODE_ENV=production -t travis-watch ./webpack_if_prod.sh
      - docker cp travis-watch-container:/src/webpack-stats.json .
      - docker cp travis-watch-container:/src/static/bundles ./static/bundles
      script: ./scripts/test/run_selenium_tests_travis.sh
      services:
        - docker
      env:
        name: Python-Selenium
    - language: node_js
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
        - export PATH="$HOME/.yarn/bin:$PATH"
      node_js:
        - "10.15.1"
      script: bash ./travis/js_tests.sh
      cache: yarn
      env:
        name: JavaScript
