version: '3.7'
services:
  web:
    volumes:
      - .:/src
      - django_media:/var/media
    environment:
      DEBUG: 'True'
      NODE_ENV: 'development'
      MICROMASTERS_USE_WEBPACK_DEV_SERVER: 'True'

  celery:
    volumes:
      - .:/src
      - django_media:/var/media
    environment:
      DEBUG: 'True'
      NODE_ENV: 'development'
      MICROMASTERS_USE_WEBPACK_DEV_SERVER: 'True'

  nginx:
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/web.conf
      - ./:/src

  sftp:
    volumes:
      - sftp_share:/home/odl/results

  watch:
    environment:
      NODE_ENV: 'development'
    volumes:
      - .:/src
      - yarn-cache:/home/mitodl/.cache/yarn


volumes:
  django_media: {}
  sftp_share: {}
  yarn-cache: {}
