version: '3.6'
services:
  selenium:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      *default-environment
      ELASTICSEARCH_INDEX: 'testindex'
      DEBUG: 'False'
      ELASTICSEARCH_DEFAULT_PAGE_SIZE: '5'

      # To silence ImproperlyConfigured when running tests
      MAILGUN_URL: http://fake.mailgun.url
      MAILGUN_KEY: fake_mailgun_key
      OPEN_DISCUSSIONS_SITE_KEY: fake_site_key
    links:
      - db
      - elastic
      - redis
      - hub
      - chrome
    ports:
      - "7000:7000"

  hub:
    image: selenium/hub:3.4.0-chromium
    environment:
      GRID_TIMEOUT: '3600'
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.4.0-chromium
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    links:
      - hub
    ports:
      - "5555:5555"
