version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432"

  redis:
    image: redis
    ports:
      - "6379"

  web:
    build:
      context: .
      dockerfile: ./travis/Dockerfile-travis-web
    command: >
      /bin/bash -c '
      sleep 3 &&
      python3 manage.py migrate &&
      ./with_host.sh python3 manage.py runserver 0.0.0.0:8079'
    environment:
      DEBUG: 'False'
      COVERAGE_DIR: htmlcov
      PORT: 8079
      NODE_ENV: 'production'
      DATABASE_URL: postgres://postgres@db:5432/postgres
      MICROMASTERS_SECURE_SSL_REDIRECT: 'False'
      MICROMASTERS_DB_DISABLE_SSL: 'True'
      ELASTICSEARCH_URL: elastic:9200
      BROKER_URL: redis://redis:6379/4
      CELERY_RESULT_BACKEND: redis://redis:6379/4
    env_file: .env
    ports:
      - "8079:8079"
    links:
      - db
      - elastic

  celery:
    image: micromasters_web
    mem_limit: 384m
    command: >
      /bin/bash -c '
      sleep 3;
      celery -A micromasters worker -B -l debug'
    volumes_from:
      - web
    environment:
      DEBUG: 'False'
      MICROMASTERS_DB_DISABLE_SSL: 'True'
      DATABASE_URL: postgres://postgres@db:5432/postgres
      BROKER_URL: redis://redis:6379/4
      CELERY_RESULT_BACKEND: redis://redis:6379/4
      ELASTICSEARCH_URL: elastic:9200
      CELERY_ALWAYS_EAGER: 'True'
    env_file: .env
    links:
      - db
      - elastic
      - redis

  elastic:
    image: elasticsearch:2.4.1
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200"
